language: node_js
node_js:
  - node
cache:
  directories:
    - ~/.npm

before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
addons:
  ssh_known_hosts: crichard.fr

before_script:
  - yarn global add expo-cli sharp-cli
  - yarn
script:
  - expo build:web

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/web-build root@crichard.fr:/var/www/universe
  on:
    branch: master
